video/video/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from videoplayer import views

urlpatterns = [
    path('', include('videoplayer.urls')),
    path('admin/', admin.site.urls),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='register'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/videoplayer/urls.py
from django.urls import path
from . import views

app_name = 'videoplayer'

urlpatterns = [
    path('', views.video_playlist, name='video_playlist'),
    path('videoplayer/<int:video_id>/', views.videoplayer, name='videoplayer'),
    path('videoplayer/asset_upload/', views.asset_upload, name='asset_upload'),
    path('videoplayer/conversion_task/', views.conversion_task, name='conversion_task'),
    path('videoplayer/conversion_task/<int:video_id>', views.conversion_task, name='conversion_task'),
]

video/videoplayer/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.
class VideoLocations(models.Model):
    file_path = models.CharField(max_length=255)
    video_name = models.CharField(max_length=200)
    video_category = models.CharField(max_length=50)
    poster_path = models.CharField(max_length=255, default='0')

    def __str__(self):
        return self.video_name


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


def user_directory_path(instance, filename):
    return datetime.utcnow().strftime('')


class VideoFileUpload(models.Model):
    video_name = models.CharField(max_length=200)
    file_item = models.FileField(upload_to='%Y%m%d%H%M%S%f')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    converted = models.BooleanField(default=False)

video/videoplayer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo, VideoFileUpload


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic',)


class AssetUploadForm(forms.ModelForm):
    class Meta:
        model = VideoFileUpload
        fields = ('video_name', 'file_item')

video/videoplayer/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import UserForm, UserProfileInfoForm, AssetUploadForm
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from .models import VideoLocations, VideoFileUpload
from .converter import converter
import pathlib
from video.settings import MEDIA_ROOT
import threading
# Create your views here.


@login_required
def video_playlist(request):
    video_items = VideoLocations.objects.all()
    return render(request, 'videoplayer/play_list.html', {"video_items": video_items})


@login_required
def videoplayer(request, video_id):
    print(video_id)
    item = VideoLocations.objects.get(id=video_id)
    return render(request, 'videoplayer/player.html', {'item': item})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('videoplayer:video_playlist'))


@login_required
def asset_upload(request):
    if request.method == 'POST':
        form = AssetUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('videoplayer:video_playlist')
    else:
        form = AssetUploadForm()
    return render(request, 'videoplayer/asset_upload.html', {'form':form})


@login_required
def remove_video(request, id):
    if request.method == 'GET':
        form = AssetUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('videoplayer:video_playlist')
    else:
        form = AssetUploadForm()
    return render(request, 'videoplayer/asset_upload.html', {'form':form})


@login_required
def conversion_task(request, video_id='None'):
    data = VideoFileUpload.objects.filter(converted=False)
    if request.method == 'GET' and video_id != 'None':
        to_be_converted = VideoFileUpload.objects.get(pk=video_id)
        to_be_converted_file = pathlib.Path(str(to_be_converted.file_item))
        to_be_converted_path = to_be_converted_file.parent
        x_thread = threading.Thread(target=converter, args=(MEDIA_ROOT / to_be_converted_path, MEDIA_ROOT / to_be_converted_file, video_id,))
        x_thread.start()

    return render(request, 'videoplayer/conversion_task.html', {'data': data})


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'videoplayer/registration.html', {'user_form': user_form,
                                                             'profile_form': profile_form,
                                                             'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('videoplayer:video_playlist'))
            else:
                HttpResponse('Account is not active!!!')
        else:
            print('Login failed!!!')
            return HttpResponse('Invalid login details provided!')
    else:
        return render(request, 'videoplayer/login.html', {})

video/templates/videoplayer/add_video.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}

<link href="{% static 'videoplayer/css/video-js.css' %}" rel="stylesheet" />

{% for path in video_items %}
        <video id="my-video"
            class="video-js vjs-default-skin"
            controls="True"
            volume="1"
            preload="true"
            autoplay="false"
            width="320"
            height="180"
            poster="{{ path.poster_path }}"
            data-setup='{}' >
            <source src="{{ path.file_path }}" type="application/x-mpegURL" />
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a
              web browser that
              <a href="https://videojs.com/html5-video-support/" target="_blank"
                >supports HTML5 video</a
              >
            </p>
          </video>
{% endfor %}

<script src="{% static 'videoplayer/js/video.min.js' %}" ></script>
<script src="{% static 'videoplayer/js/videojs-contrib-hls.min.js' %}" ></script>

<script>
var player = videojs('my-video', {
  responsive: true
});
player.play();
</script>
{% endblock  %}

video/templates/videoplayer/asset_upload.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'videoplayer:video_playlist' %}">Return to home</a></p>

{% endblock  %}

video/templates/videoplayer/base.html
{% load static %}
<!DOCTYPE html>
<head>
<meta charset="UTF-8">
<html lang="en">
<link rel="stylesheet" href="{% static 'videoplayer/css/style.css' %}">
<link rel="stylesheet" href="{% static 'videoplayer/css/bootstrap.min.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'videoplayer/images/video_favicon.ico' %}"/>
    <title>Video Player</title>
</head>
<body>
<div class="container">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">&nbsp;Video</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'videoplayer:video_playlist' %}">Home</a>
        </li>
  {% if user.is_superuser %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'videoplayer:asset_upload' %}">Add video</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'videoplayer:conversion_task' %}">Conversion task</a>
        </li>
  {% endif %}
        </ul>
    </div>

  {% if user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'user_logout' %}">Logout</a>

  {% endif %}

</nav>
{% block body_block %}{% endblock %}
</div>
<script src="{% static 'videoplayer/js/bootstrap.bundle.min.js' %}" ></script>
</body>
</html>

video/templates/videoplayer/conversion_task.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Convert?</th>
    </tr>
  </thead>
  <tbody>
  {% for i in data %}


    <tr>
      <td>{{ i.video_name }}</td>
      <td><a href="{{ i.id }}"><img src = "{% static 'videoplayer/images/play.svg' %}"></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock  %}

video/templates/videoplayer/login.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Sign In </h2>

    <!-- Login Form -->
    <form method="POST" action="{% url 'user_login' %}">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">
      <label for="password">Password::</label>
      <input type="password" name="password" placeholder="Enter Password">

      <input type="submit" value="login" />
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      Forgot your Password? Contact admin.
    </div>

  </div>
</div>
{% endblock  %}

video/templates/videoplayer/play_list.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}

<link href="{% static 'videoplayer/css/video-js.css' %}" rel="stylesheet" />
<section id="team" class="pb-5">
    <div class="container">
        <h3 class="section-title">Videos</h3>
        <div class="row">
{% for path in video_items %}
            <div class="col-xs-12 col-sm-6 col-md-4">

                            <div class="card" id="container">
                                <div class="card-body text-center">
                                    <a href="/videoplayer/{{ path.id }}">
                                    <p><img class="img-fluid" src="{{ path.poster_path }}" alt="{{ path.video_name }}"></p>
                                    <h4 class="card-title">{{ path.video_name }}</h4>
                                    </a>
                                    <img src="{% static 'videoplayer/images/trash.svg' %}" id="img2">
                                </div>
                            </div>
            </div>

{% endfor %}
        </div>
    </div>
</section>
{% endblock  %}

video/templates/videoplayer/player.html
{% extends "videoplayer/base.html" %}
{% block body_block %}
{% load static %}

<link href="{% static 'videoplayer/css/video-js.css' %}" rel="stylesheet" />
<div class="container">
        <video id="my-video"
            class="video-js vjs-default-skin"
            controls="True"
            volume="1"
            preload="true"
            autoplay="false"
            width="320"
            height="180"
            poster="{{ item.poster_path }}"
            data-setup='{}' >
            <source src="{{ item.file_path }}" type="application/x-mpegURL" />
            <p class="vjs-no-js">
              To view this video please enable JavaScript, and consider upgrading to a
              web browser that
              <a href="https://videojs.com/html5-video-support/" target="_blank"
                >supports HTML5 video</a
              >
            </p>
          </video>
        <input type=button value="Previous Page" onClick="location.href='{% url 'videoplayer:video_playlist' %}'">
</div>
<script src="{% static 'videoplayer/js/video.min.js' %}" ></script>
<script src="{% static 'videoplayer/js/videojs-contrib-hls.min.js' %}" ></script>

<script>
var player = videojs('my-video', {
  responsive: true
});
player.play();
</script>
{% endblock  %}

video/templates/videoplayer/registration.html
{% extends "videoplayer/base.html" %}
{% load static %}
{% block body_block %}
<div class="wrapper fadeInDown">
{% if registered %}
    <h1>Thank you for registering</h1>
{% else %}
    <h1>Register here.</h1>
    <h3>Fill out the form:</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
{% endif %}
</div>
{% endblock  %}